/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Arrays; //Biblioteca para facilitar a inicialização da matriz utilizando o Arrays.fill()

public class Main{
    public static void main(String[] args) {
        String[][] tabuleiro = new String[10][10];
        for (int i = 0; i < 10; i++) {
            Arrays.fill(tabuleiro[i], "."); //Para cada linha do tabuleiro, preecha cada coluna com "."
        }
    }
}
