/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Scanner;

public class App {

    static boolean buscaNavio (String linha){
        return switch (linha) { //Retorna falso se não for barco conhecido ou se possuir bloco de água
            case "N" -> true;
            case "S" -> true;
            case "C" -> true;
            case "E" -> true;
            case "P" -> true;
            case "." -> true;
            default -> false;
        };
    }

    /*Varre vetor buscando navio inválido, ignora elementos de água e de navios conhecidos,
    encerra programa se achar qualquer caracter que não se enquadrad nos discritos anteriormente*/
    static void temNavioDesconhecido (String[] linha){
        for (int i = 0; i < linha.length; i++) {
            if(!buscaNavio(linha[i])){
                System.out.println("Tabuliero inválido, há navio ou caractere desconhecido");
                System.exit(1);
            }
        }
    }

    //Se linha do tabuleiro tiver uma quantidade diferente de 10 linhas, ou, se quatidade de linhas for maior que 10
    static void temTamanho10x10 (String[] linha, int qtd_linhas, boolean menos10linhas){
        if (linha.length != 10 || qtd_linhas > 10 || menos10linhas) {
            System.out.println("Tabuliero inválido, não possui tamanho 10x10");
            System.exit(1);
        }
    }

    static void leArquivo(Scanner arquivo, String[][] tabuleiro){
        int qtd_linhas = 0;
        boolean menos10linhas = false;
        String[] linha = null;
        while(arquivo.hasNextLine()){
            qtd_linhas++;
            linha = arquivo.nextLine().split(" ");
            temTamanho10x10(linha, qtd_linhas, menos10linhas);
            temNavioDesconhecido(linha);
        }
        if(qtd_linhas < 10){
            menos10linhas = true;
            temTamanho10x10(linha,qtd_linhas,menos10linhas);
        }
    }

    public static void main(String[] args) {
        Scanner arquivo = new Scanner(System.in);
        String[][] tabuleiro = new String[10][10];
        leArquivo(arquivo, tabuleiro);
        System.out.println("Tabuleiro válido");
    }
}
